apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-api
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: platform-api
  template:
    metadata:
      labels:
        app: platform-api
    spec:
      containers:
        - name: platform-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8000

          env:
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: ENV

            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: APP_NAME